### ISSUE TITLE
Request cache stopped working?

### ISSUE THREAD

**Issue by amotl** [panodata/grafana-wtf#132]
## Problem

It looks like the request cache stopped working? When invoking grafana-wtf on play.grafana.org, the program requests data over and over again. That is especially hard on such a huge Grafana installation, where it takes almost one and a half minutes to acquire all the metadata.

```
export GRAFANA_URL=https://play.grafana.org
grafana-wtf info --format=yaml

Fetching dashboards in parallel with 5 concurrent request/s]

  4%|█▏                   | 67/1537 [00:03<01:26, 16.99it/s]
```

```yaml
grafana:
  version: 11.1.0-68793
  url: https://play.grafana.org
statistics: {}
summary:
  dashboard_panels: 9299
  dashboard_annotations: 1501
  dashboard_templating: 1349
```

## Thoughts

Is it related to the switchover to [Niquests](https://niquests.readthedocs.io/), because it does not harmonize with [requests-cache](https://requests-cache.readthedocs.io/) well, yet?

- GH-125

/cc @Ousret
